
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-webserver:
    image: apache/airflow:2.6.3
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow  # Actualizado
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=2a1e648e0346b9503a1decfed97e3869
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: >
      bash -c "
      sleep 15 &&
      airflow db init &&
      airflow users create --username admin --firstname Nombre --lastname Apellido --role Admin --email admin@example.com --password admin &&
      airflow webserver
      "

  airflow-scheduler:
    image: apache/airflow:2.6.3
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow  # Actualizado
      - AIRFLOW__WEBSERVER__SECRET_KEY=2a1e648e0346b9503a1decfed97e3869
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    command: >
      bash -c "sleep 40 && airflow scheduler"

  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_LOAD_EXAMPLES=no
      - SUPERSET_ADMIN_USERNAME=admin
      - SUPERSET_ADMIN_PASSWORD=admin
      - SUPERSET_DATABASE_URI=postgresql+psycopg2://airflow:airflow@postgres:5432/taxi_data
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
      - ./superset:/app/superset_home
    depends_on:
      - postgres
    command: >
      /bin/bash -c "
      sleep 40 &&
      superset fab create-admin --username admin --firstname admin --lastname admin --email admin@admin.com --password admin &&
      superset db upgrade &&
      superset init &&
      superset import-dashboards -p /app/superset_home/dashboards.zip --username admin &&
      superset run -h 0.0.0.0 -p 8088
      "

  rasa:
    image: rasa/rasa:3.6.0-full
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    command: run -m models --enable-api --cors "*" --debug --credentials credentials.yml
    depends_on:
    - postgres 

  action_server:
    image: rasa/rasa:3.6.0-full
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app
    command: run actions
    depends_on:
    - postgres 


  webchat:
    build:
      context: .
      dockerfile: Dockerfile-webchat
    ports:
      - "8081:80"  
    depends_on:
      - rasa

volumes:
  pgdata:
